### ISSUE TITLE
Packing the project

### ISSUE THREAD

**Issue by flyingtango** [ocean-data-qc/ocean-data-qc#12]
Hi, very nice work!
How can I pack the project to exe or dmg? Is it using pyinstaller? Hope the specific packaging process can be provided, thanks!

**Comment by chesucr** [comment]
Hello !! Thank you !!

We have used [Electron Builder](https://www.electron.build/) as you can see in the [`package.json`](https://github.com/ocean-data-qc/ocean-data-qc/blob/master/ocean_data_qc_js/package.json#L70) file.

You can create the exe file following [these guidelines](https://github.com/ocean-data-qc/ocean-data-qc/blob/master/docs/Upgrade%20Guidelines.md), just skip steps 1 and 5. For dmg, instead of `dist_win`, you can use `dist_mac`. Fyi those shortcuts are implemented in the [package.json](https://github.com/ocean-data-qc/ocean-data-qc/blob/master/ocean_data_qc_js/package.json#L12) file as well
